# Generated by Django 2.1.7 on 2019-02-25 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='additional_info',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(verbose_name='Data Zakończenia'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data Rozpoczęcia'),
        ),
    ]
