# Generated by Django 2.1.7 on 2019-02-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Marka')),
                ('name', models.CharField(max_length=255, verbose_name='Model')),
                ('segment', models.CharField(max_length=255, verbose_name='Segment')),
                ('manufacture_year', models.IntegerField(default=2019, verbose_name='Rok produkcji')),
                ('capacity', models.FloatField(verbose_name='Pojemność')),
                ('price', models.FloatField(verbose_name='Cena')),
            ],
            options={
                'verbose_name': 'Samochód',
                'verbose_name_plural': 'Samochody',
                'ordering': ['manufacture_year'],
            },
        ),
    ]
