# Generated by Django 2.1.7 on 2019-02-23 17:03

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0.0'), default_currency='PLN', max_digits=14),
        ),
    ]
