# Generated by Django 2.1.7 on 2019-02-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, default='/news/static/img/no-photo-car.jpg', null=True, upload_to=None, verbose_name='Zdjęcie'),
        ),
    ]
