# Generated by Django 2.1.7 on 2019-02-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20190221_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, default='news/static/img/no-photo-car.jpg', null=True, upload_to='media', verbose_name='Zdjęcie'),
        ),
    ]
