# Generated by Django 2.1.7 on 2019-02-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20190221_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, default='no-photo-car.jpg', null=True, upload_to=None, verbose_name='Zdjęcie'),
        ),
    ]
