# Generated by Django 2.1.7 on 2019-02-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20190221_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, default='no-photo-car.jpg', null=True, upload_to='', verbose_name='Zdjęcie'),
        ),
    ]
